swagger: "2.0"
info:
  version: "1.0"
  title: "RTK Planner"
  description: "This is for path planning."

paths:
  /rover/register:
    post:
      description: "Register device in application."
      operationId: "rover.register"
      parameters:
        - name: mac
          in: body
          description: "Rover MAC address."
          schema:
            type: string
            required:
              - mac
            properties:
              mac:
               type: string
      responses:
        200:
          description: "Rover already registered."

        400:
          $ref: "#/responses/400Error"

  /rover/update_gps1:
    post:
      description: "Register device in application."
      operationId: "rover.update_gps"

      parameters:
        - name: gnssdata
          in: body
          description: "GNSS possition data."
          schema:
            $ref: "#/definitions/GNSSdata"

      responses:
        200:
          description: "Rover already registered."

        400:
          $ref: "#/responses/400Error"

  /rover/{name}:
    get:
      description: "Get rover by name."
      operationId: "rover.get_by_name"

      parameters:
        - name: name
          in: path
          required: true
          type: string

      responses:
        200:
          description: "Successfully get rover by name"
          schema:
            $ref: "#/definitions/Rover"
        400:
          $ref: "#/responses/400Error"

  /rover:
    get:
      description: "Get all rovers."
      operationId: "rover.get_all"

      responses:
        200:
          description: "Successfully get rovers."

definitions:
  Rover:
    type: object
    required:
      - mac
      - name
    properties:
      mac:
        type: string
      name:
        type: string
      status:
        type: integer
      last_active:
        type: string

  GNSSdata:
    type: object
    required:
      - fix_status
      - latitude
      - longitude
    properties:
      fix_status:
        type: string
      latitude:
        type: string
      longitude:
        type: string
      lat_raw:
        type: string
      lon_raw:
        type: string
      speed:
        type: string
      course:
        type: string
      time_utc:
        type: string
      last_update:
        type: string

responses:
  400Error:
    description: "Invalid request."
    schema:
      type: object
      properties:
        message:
          type: string
